name: .NET Build and Test

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Triggers on push to main branch
  pull_request:
    branches:
      - main  # Triggers on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Switch to Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Setup .NET
      uses: actions/setup-dotnet@v3  # Sets up the .NET SDK
      with:
        dotnet-version: '3.1.x'  # Adjust the .NET version if needed

    - name: Restore dependencies
      run: dotnet restore  # Restores dependencies

    - name: Build the project
      run: dotnet build --configuration Release  # Builds the project

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal  # Runs tests without rebuilding

    - name: Publish Build Artifacts
      if: success()  # Only publish if the previous steps succeeded
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          **/bin/Release/netcoreapp3.1/publish/
